### ISSUE TITLE
Add doc blurb about expanding cluster with Ansible-managed environment

### ISSUE THREAD

**Issue by hcoyote** [redpanda-data/redpanda-ansible-collection#24]
Expanding/adding brokers to an existing ansible managed cluster should work by adding more nodes into the redpanda section of the hosts.ini (or however the user is managing host class membership).

It's not obvious that we support this though, so let's add something to the README to indicate that it can be done and what's needed for it.

[Slack Message](https://redpandadata.slack.com/archives/C049AE7V4U8/p1686939079782769?thread_ts=1686939079.782769&cid=C049AE7V4U8)

**Comment by gene-redpanda** [comment]
Fixed with link to docs page
